# Site settings
title: Kugghuset
email: hello@kugghuset.se
tel: +46 8 39 26 60
googleAnalytics: UA-69299979-1
timezone: 'Europe/Stockholm'
description: > # this means to ignore newlines until "baseurl:"
  We talk about development, business intelligence, data integration and data visulization.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kugghuset.se/" # the base hostname & protocol for your site
github_username: Kugghuset

# Build settings
markdown: kramdown
highlighter: pygments

exclude:
  - gulpfile.js
  - /node_modules